apiVersion: "v1"
kind: "Service"
#For internal VPC
metadata:
  annotations:
    networking.gke.io/load-balancer-type: "Internal"
  name: "neo4jbrowser-service"
  namespace: "default"
spec:
  ports:
  - protocol: "TCP"
    port: 7474
    targetPort: 80
  selector:
    app: "neo4jbrowser"
  type: "LoadBalancer"
  #loadBalancerIP: ""
